# Generated by Django 5.2.7 on 2025-11-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kopalnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rodzaj', models.CharField(max_length=50)),
                ('wydobywany_material', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Przenosnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oddzial', models.CharField(blank=True, max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('dlugosc_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transportowany_material', models.CharField(blank=True, max_length=50)),
                ('predkosc_tasmy_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kat_nachylenia_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('liczba_nadaw', models.IntegerField(default=0)),
                ('liczba_odbiorow', models.IntegerField(default=0)),
                ('pochylniany', models.BooleanField(default=False)),
                ('liczba_segmentow', models.IntegerField(default=0)),
                ('data_ostatniego_wydruku', models.DateField(blank=True, null=True)),
                ('kopalnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przenosniki', to='rd.kopalnia')),
            ],
        ),
        migrations.CreateModel(
            name='Nadawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ulozenie', models.CharField(blank=True, max_length=50)),
                ('krata_zsypowa', models.BooleanField(default=False)),
                ('przenosnik_odbierajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nadawy_odbierajace', to='rd.przenosnik')),
                ('przenosnik_podajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nadawy_podajace', to='rd.przenosnik')),
            ],
        ),
        migrations.CreateModel(
            name='MontazTasmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('typ', models.CharField(blank=True, max_length=30)),
                ('uwagi', models.TextField(blank=True)),
                ('przenosnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montaze_tasm', to='rd.przenosnik')),
            ],
        ),
        migrations.CreateModel(
            name='Tasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=50)),
                ('szerokosc_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('dlugosc_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wytrzymalosc_kN_na_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('srednica_linki_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grubosc_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('okladka_gorna_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('okladka_dolna_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stan', models.CharField(blank=True, max_length=20)),
                ('data_produkcji', models.DateField(blank=True, null=True)),
                ('data_regeneracji', models.DateField(blank=True, null=True)),
                ('przewidywana_zywotnosc_m', models.IntegerField(blank=True, null=True)),
                ('pierwszy_montaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasmy_jako_pierwszy_montaz', to='rd.montaztasmy')),
            ],
        ),
        migrations.AddField(
            model_name='montaztasmy',
            name='tasma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montaze', to='rd.tasma'),
        ),
        migrations.CreateModel(
            name='Zlacze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=50)),
                ('dlugosc_m', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('skosnosc_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('liczba_stopni', models.IntegerField(blank=True, null=True)),
                ('data_wykonania', models.DateField(blank=True, null=True)),
                ('data_usuniecia', models.DateField(blank=True, null=True)),
                ('wykonawca', models.CharField(blank=True, max_length=100)),
                ('pozycja_od_poczatku_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('przenosnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlacza', to='rd.przenosnik')),
                ('tasma_przed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zlacza_przed', to='rd.tasma')),
                ('tasma_za', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zlacza_za', to='rd.tasma')),
            ],
        ),
        migrations.AddField(
            model_name='montaztasmy',
            name='zlacze_przed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montaze_przed', to='rd.zlacze'),
        ),
        migrations.AddField(
            model_name='montaztasmy',
            name='zlacze_za',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montaze_za', to='rd.zlacze'),
        ),
    ]
