# Generated by Django 5.2.7 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kopalnia',
            options={'verbose_name': 'Kopalnia', 'verbose_name_plural': 'Kopalnie'},
        ),
        migrations.AlterModelOptions(
            name='montaztasmy',
            options={'verbose_name': 'Montaż taśmy', 'verbose_name_plural': 'Montaże taśm'},
        ),
        migrations.AlterModelOptions(
            name='nadawa',
            options={'verbose_name': 'Nadawa', 'verbose_name_plural': 'Nadawy'},
        ),
        migrations.AlterModelOptions(
            name='przenosnik',
            options={'verbose_name': 'Przenośnik', 'verbose_name_plural': 'Przenośniki'},
        ),
        migrations.AlterModelOptions(
            name='tasma',
            options={'verbose_name': 'Taśma', 'verbose_name_plural': 'Taśmy'},
        ),
        migrations.AlterModelOptions(
            name='zlacze',
            options={'verbose_name': 'Złącze', 'verbose_name_plural': 'Złącza'},
        ),
        migrations.RemoveField(
            model_name='tasma',
            name='pierwszy_montaz',
        ),
        migrations.AddField(
            model_name='tasma',
            name='pierwszy_montaz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='montaztasmy',
            name='typ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='montaztasmy',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nadawa',
            name='ulozenie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='przenosnik',
            name='liczba_nadaw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przenosnik',
            name='liczba_odbiorow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przenosnik',
            name='liczba_segmentow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przenosnik',
            name='oddzial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='przenosnik',
            name='transportowany_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasma',
            name='stan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zlacze',
            name='dlugosc_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zlacze',
            name='wykonawca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
