# Generated by Django 5.2.7 on 2025-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd', '0002_alter_kopalnia_options_alter_montaztasmy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasma',
            name='zywotnosc_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
